import type { NextPage } from "next";
import Head from "next/head";
import { About, Hero, Portfolio, Services } from "../components/sections";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Alicia | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="space-y-32 md:space-y-40">
        <Hero />
        <Services />
        <Portfolio />
        <About />
      </div>
    </div>
  );
};

export default Home;
